### PR TITLE
Supports check of wildcard certs

### PR DESCRIPTION
**Pull request by michaelpporter**
Adds support to check for wildcard certs to not re-make them on subsequent runs

### CODE REVIEW

**Comment by geerlingguy** [comment]
Nice! And if you don't mind my asking, are you able to request/create wildcard certs with this role as well? (Or do you use a different mechanism for the initial generation?)

Reference: https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

I need to do a wildcard at some point for one of my services, I just haven't gotten around to _doing_ it yet and I don't know if there are any changes to this role that could make it simpler. I'll definitely merge this when I get a chance though!

**Comment by michaelpporter** [comment]
Yes and no. To use certbot for wildcards you need to install the [DNS Plugins](https://certbot.eff.org/docs/using.html#dns-plugins). 

I built a [playbook for Cloudflare](https://github.com/michaelpporter/ansible-role-certbot-cloudflare).

```yaml
# Defaults for Cloudflare
certbot_cloudflare_email: "cloudflare@example.com"
# Your Global API Key from your account
# ansible-vault encrypt_string 'cloudflareAPIKey' --name 'certbot_cloudflare_api_key'
certbot_cloudflare_api_key: ''
certbot_create_standalone_stop_services: []
certbot_create_if_missing: yes

# Required vars, change `--dns-cloudflare` to the needed plugin. 
certbot_create_command: "certbot certonly --noninteractive --dns-cloudflare --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
certbot_create_method: standalone
certbot_install_from_source: yes
certbot_repo: https://github.com/certbot/certbot.git
certbot_version: master
certbot_keep_updated: yes
```

The the steps are:

1. Add your wildcard domain to the DNS with the IP from the server. I do this manually, though we might be able to use Ansible to create the domain [Cloudflare](https://docs.ansible.com/ansible/2.5/modules/cloudflare_dns_module.html), [route 53](https://docs.ansible.com/ansible/2.5/modules/route53_module.html#route53-module) or [Digital Ocean](https://docs.ansible.com/ansible/2.5/modules/digital_ocean_domain_module.html#digital-ocean-domain-module)
1. Install required python packages 
2. Run `geerlingguy.pip`
3. Run `geerlingguy.certbot` `certbot_install_from_source: yes` and `certbot_certs: []`
4. Install the DNS Plugin needed `cd {{certbot_dir}}/certbot-dns-cloudflare && python setup.py install`
5. Create the [ini settings](https://github.com/michaelpporter/ansible-role-certbot-cloudflare/blob/990f8e22160c145458b553f4194643758816769a/tasks/main.yml#L41) 
6. Run `geerlingguy.certbot` `certbot_certs: domain: *.[optional subdomin].example.com`

**Comment by michaelpporter** [comment]
P.S. After building the playbook for Cloudflare, I think it would be better to make one for each of the services. Each service has a distinct plugin and settings file. I could also change `/etc/letsencrypt/cli.ini` to a base template then use `lineinfile` to add multiple services based on vars. 

The issue I have is how to test them if you are not using them yourself?

**Comment by geerlingguy** [comment]
Hmm, that sounds a little more involved, and might just be a matter of documentation (especially since, as you say, I wouldn't be able to test them all since I don't use them all myself, and Travis CI couldn't do it either!).

Would you consider writing a blog post (or series of posts) on how you use this role in your wildcard playbooks, and I can link to it under a new 'Wildcard Certificates' section in the README? That might be a more reasonable approach, maintenance-wise.

**Comment by geerlingguy** [comment]
@michaelpporter - I added a section in the README, and would love to make it better for others who wish to request wildcard certs (heck, I may need to at some point for one of my projects!). See commit: https://github.com/geerlingguy/ansible-role-certbot/commit/a2348fdd64caf94e04846c7a07c0b8247312742f

**Comment by michaelpporter** [comment]
@geerlingguy I agree, easier is a goal. 

I followed the [links](https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579) and [ACME Client Implementations](https://letsencrypt.org/docs/client-options/) mentions [Ansible acme_certificate](https://docs.ansible.com/ansible/latest/modules/acme_certificate_module.html). I will do some testing. I found an article, [Wildcard LetsEncrypt renewal with Ansible and Memset](https://dickingwithdocker.com/2018/08/wildcard-letsencrypt-renewal-with-ansible-and-memset/) that could serve a guide.

**Comment by michaelpporter** [comment]
@geerlingguy I have a blog post about the process [Creating A Let’s Encrypt Wildcard Cert With Ansible](https://www.michaelpporter.com/2018/09/creating-a-wildcard-cert-with-ansible/)

**Pull request merged**
