### PR TITLE
Issue #134: Snap install method.

### LINKED ISSUE #134: certbot-auto is being deprecated and does not work on Ubuntu 18.04.5
Per https://github.com/certbot/certbot/issues/7941#issuecomment-619177149 the certbot-auto functionality is being deprecated and does not work on 20.04:

```

TASK [certbot : Generate new certificate if one doesn't exist.] ****************
--
21:34:37 |   | fatal: [hostname]: FAILED! => {
21:34:37 |   | "changed": true,
21:34:37 |   | "cmd": [
21:34:37 |   | "/opt/certbot/certbot-auto",
21:34:37 |   | "certonly",
21:34:37 |   | "--standalone",
21:34:37 |   | "--noninteractive",
21:34:37 |   | "--agree-tos",
21:34:37 |   | "--email",
21:34:37 |   | "user@example.com",
21:34:37 |   | "-d",
21:34:37 |   | "example.com"
21:34:37 |   | ],
21:34:37 |   | "delta": "0:00:00.030074",
21:34:37 |   | "end": "2020-12-02 02:34:37.844875",
21:34:37 |   | "rc": 1,
21:34:37 |   | "start": "2020-12-02 02:34:37.814801"
21:34:37 |   | }
21:34:37 |   |  
21:34:37 |   | STDOUT:
21:34:37 |   |  
21:34:37 |   | Skipping bootstrap because certbot-auto is deprecated on this system.
21:34:37 |   | WARNING: couldn't find Python 2.7+ to check for updates.
21:34:37 |   | Your system is not supported by certbot-auto anymore.
21:34:37 |   | Certbot cannot be installed.
21:34:37 |   | Please visit https://certbot.eff.org/ to check for other alternatives.
```

### PR DESCRIPTION
**Pull request by geerlingguy**
Fixes #134.﻿

### CODE REVIEW

**Comment by geerlingguy** [comment]
```yaml
- name: Ensure snapd is enabled.
  systemd:
    name: snapd.socket
    enabled: true
```

Might need some adjustment. The recommended command in the docs is:

```
sudo systemctl enable --now snapd.socket
```

**Comment by guimaluf** [comment]
Using certbot snap seems to also change the way cron job should run. 

While using snap and this role cron job I'm getting a couple of errors.

```
cmd_run.go:994: WARNING: cannot create user data directory: failed to
verify SELinux context of /root/snap: exec: "matchpathcon": executable
file not found in $PATH
cannot snap-exec: cannot exec
"/var/lib/snapd/snap/certbot/952/bin/python3": no such file or
directory

cmd_run.go:994: WARNING: cannot create user data directory: failed to
verify SELinux context of /root/snap: exec: "matchpathcon": executable
file not found in $PATH
Failed to renew certificate vhpc-gb637-dev.srcp.hpc.cam.ac.uk with
error: Problem binding to port 80: Could not bind to IPv4 or IPv6.
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/mydomain.co/fullchain.pem
(failure)
1 renew failure(s), 0 parse failure(s)
```

Checking certbot documentation it seems like they're using systemd-timer to trigger the renewing process rather then cron.

Thus `certbot_auto_renew_options` might need go  to `/etc/letsencrypt/renewal/<domain>.conf` instead of corn command line.

**Comment by guimaluf** [comment]
I've added up a few things here:  #141

**Comment by scottsb** [comment]
> ```yaml
> - name: Ensure snapd is enabled.
>   systemd:
>     name: snapd.socket
>     enabled: true
> ```
> 
> Might need some adjustment. The recommended command in the docs is:
> 
> ```
> sudo systemctl enable --now snapd.socket
> ```

You are correct. Just submitted #146 to fix.

**Pull request merged**
