### PR TITLE
Ensure ubuntu distributions get the latest version of certbot

### PR DESCRIPTION
**Pull request by triplepoint**
- Remove the non-standard Ubuntu 16.04 package and script name (letsencrypt vs certbot)
- Add the EFF-maintained certbot PPA

This is in response to an email I started receiving from letsencrypt.org, part of which includes:
```
Your Let's Encrypt client used ACME TLS-SNI-01 domain validation to issue
a certificate in the past 60 days. Below is a list of names and IP
addresses validated (max of one per account):

-REDACTED-

TLS-SNI-01 validation is reaching end-of-life. It will stop working
temporarily on February 13th, 2019, and permanently on March 13th, 2019.
Any certificates issued before then will continue to work for 90 days
after their issuance date.

You need to update your ACME client to use an alternative validation
method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your
certificate renewals will break and existing certificates will start to
expire.
```

### CODE REVIEW

**Comment by triplepoint** [comment]
@geerlingguy Any interest in this being landed?

**Comment by ericsysmin** [comment]
@triplepoint I just did a massive rewrite of installs, you can try my PR if you'd like maybe it fixes your problem?

**Comment by ericsysmin** [comment]
@triplepoint https://github.com/geerlingguy/ansible-role-certbot/pull/108

**Comment by triplepoint** [comment]
Sorry, I can't easily test this because I'm not using this role any more.  I moved on to letting Traefik handle the cert reprovisioning with its ACME support.

**Comment by ericsysmin** [comment]
@geerlingguy you can probably close this one then

**Pull request closed without merging**
