### PR TITLE
do not use cron when installing from distribution on Debian

### PR DESCRIPTION
**Pull request by xiruizhao**
Debian distribution package provides a systemd timer for certificate auto renewal

### CODE REVIEW

**Comment by maxtruxa** [comment]
I work around this by setting `certbot_auto_renew: false` on Debian, but it sure would be nice to have this behavior by default.

**Comment by maxtruxa** [comment]
Still relevant.

**Comment by evilhamsterman** [comment]
I think a better way of doing this would be to create a file in vars called Debian.yml with the line `certbot_auto_renew: false`. @geerlingguy's roles will pull from vars files named after the ansible_os_family for distro or family specific features.

**Comment by evilhamsterman** [comment]
Still relevant

**Comment by rotanid** [comment]
still relevant

**Comment by markstos** [comment]
I ran this playbook on Ubuntu and then used `systemctl list-timers` to confirm `certbot.timer` was present and runing and it was. I recommend merging this.

**Comment by evilhamsterman** [comment]
@geerlingguy I know you are very busy but this is a very simple fix that has been sitting for a long time. Can you either accept this PR or add `certbot_auto_renew: false` to your Debian.yml vars file?

**Comment by xiruizhao** [comment]
See https://packages.debian.org/bullseye/all/certbot/filelist

**Comment by xiruizhao** [comment]
Distribution package users with systemd timers should turn off certbot_auto_renew.

**Comment by markstos** [comment]
This is commonly installed directly with Ansible. The role supports Debian already, and replacing systemd timers with cron a better choice on Debian and should be set in the role itself.

**Pull request closed without merging**
