### PR TITLE
Replaces cron job with a systemd service and timer

### PR DESCRIPTION
**Pull request by nkakouros**
The reason is to allow to robustly reboot the web service to cater for when certificates are actually renewed. Also, it offers easy log access via journalctl.

### CODE REVIEW

**Comment by tterranigma** [comment]
I just realized that Centos6 does not use systemd (ubuntu 14.04 is dead anyways).

**Comment by stefan2904** [comment]
Nevertheless, this is still a nice feature! Would love to have it implemented & merged for systemd distros in some way or another.

**Comment by tterranigma** [comment]
I updated this PR to optionally install a systemd service if the user wants it. This should overcome the Centos issue.

**Comment by nkakouros** [comment]
Closing this as the maintainer seems uninterested. @stefan2904 or anyone else interested, you can use my fork of the role (that's what I do).

**Pull request closed without merging**
