### PR TITLE
Add support for yum, dnf, apt, pip installs and plugin installs

### PR DESCRIPTION
**Pull request by ericsysmin**
PR that provides multiple install types, as well as adding support of PPA for later newer versions of cerbot.

### CODE REVIEW

**Comment by ericsysmin** [comment]
@geerlingguy please review this PR, I've added many tests https://travis-ci.org/github/geerlingguy/ansible-role-certbot/builds/680289901 which verify the multiple scenarios.

**Comment by colans** [comment]
@ericsysmin Does this handle the #2 case, or does that still need to be solved if this gets in?

**Comment by ericsysmin** [comment]
@colans this will allow you to install the nginx and other plugins including route53, however, passing those values to your command is not being done here. Once @geerlingguy merges this PR, the you could edit the command to run with nginx flags, or just run it as a param, this is what I do for my webserver
```
 certbot_create_standalone_stop_services: httpd
 certbot_auto_renew_options: "--dns-route-53 --quiet --no-self-upgrade --deploy-hook 'systemctl reload httpd'"

```

**Comment by ericsysmin** [comment]
@geerlingguy any chance to look at this one?

**Comment by colans** [comment]
Still relevant.

**Comment by ericsysmin** [comment]
@geerlingguy any chance you can look at this?

**Comment by colans** [comment]
Still relevant.

**Comment by geerlingguy** [comment]
Every time I come back to this PR, I spend a lot of time thinking whether I should consider merging it or not, commenting on it or not, etc. I mostly haven't closed it because I do see how it could be valuable to have more flexibility here.

But I just don't like the vast complexity it adds (IMO) in terms of trying to test and figure out exactly how it's getting installed—and that's typically my lowest concern when I'm trying to configure certbot. 99% of the time I try to install from source, and the other 1% now I skip system package managers since I've been burned there and go with pip.

**Comment by colans** [comment]
:wave:

**Comment by colans** [comment]
:wave:

**Comment by colans** [comment]
:wave:

**Comment by colans** [comment]
:wave:

**Comment by colans** [comment]
wave

**Comment by ericsysmin** [comment]
I mean I stopped using certbot recently due to the massive cert issue they had last year. @geerlingguy do you want to close this or make the changes? I don't even know if this will work anymore...haha

**Comment by colans** [comment]
:wave:

**Pull request closed without merging**
