### PR TITLE
Add support for issuing fake certificates from letsencrypt staging en…

### PR DESCRIPTION
**Pull request by nekeal**
This PR adds support for issuing fake certificates from letsencrypt staging environment. It also deletes fake certificates when `certbot_staging_mode` variable is set to `false` to ensure that valid certificate will be issued.

Solves #23

### CODE REVIEW

**Comment by febeling** [comment]
This is still very interesting.

**Comment by nekeal** [comment]
@geerlingguy I think that you should take a look for this PR instead of letting the stale-bot decide:)

**Comment by nekeal** [comment]
I won't give up:)

**Comment by ADefossez-Zenika** [comment]
Very usefull to me ! Don't give up, you're right :D

**Pull request closed without merging**
